/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package d156.pdvfarmacia;

import java.sql.SQLException;
import java.util.ArrayList;

import javax.swing.JOptionPane;

import DAO.ProdutoDAO;
import Model.Cliente;
import Model.Produto;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 * Classe representa a classe de cadastro de produtos da farmácia
 * @author everyone
 * @see ProdutoDAO
 */

public class CadastroProduto extends javax.swing.JFrame {

    /**
     * Creates new form CadastroProduto
     */
    public CadastroProduto() {
        initComponents();
        atualizarTabela();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblProdutos = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        txtProduto = new javax.swing.JFormattedTextField();
        txtCodigo = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPreço = new javax.swing.JFormattedTextField();
        btnUtilizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produtos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName(""); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CADASTRO DE PRODUTOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("AppleGothic", 1, 24))); // NOI18N
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setName(""); // NOI18N

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setName(""); // NOI18N

        jTblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Quantidade", "Preço"
            }
        ));
        jScrollPane1.setViewportView(jTblProdutos);

        btnBuscar.setText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscar.setName(""); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAlterar.setName(""); // NOI18N
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnDeletar.setText("Deletar");
        btnDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDeletar.setName(""); // NOI18N
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCadastrar.setName(""); // NOI18N
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        txtProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtProduto.setName(""); // NOI18N
        txtProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdutoActionPerformed(evt);
            }
        });

        txtCodigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtCodigo.setName(""); // NOI18N
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        jLabel1.setText("Produto:");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setName(""); // NOI18N

        jLabel2.setText("Código:");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setName(""); // NOI18N

        jLabel3.setText("Quantidade:");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel3.setName(""); // NOI18N

        txtQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtQuantidade.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtQuantidade.setName(""); // NOI18N

        jLabel4.setText("Preço:");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setName(""); // NOI18N

        txtPreço.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00"))));

        btnUtilizar.setText("Utilizar Produto");
        btnUtilizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUtilizar.setEnabled(false);
        btnUtilizar.setName(""); // NOI18N
        btnUtilizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUtilizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPreço, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnDeletar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnUtilizar, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPreço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(btnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeletar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUtilizar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdutoActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        /*
        verificar se as caixas estão vaizas
        */
        Produto produto = new Produto();
        if(txtCodigo.getText().isEmpty() || txtCodigo.getText() == null){
            btnCadastrar.setText("Salvar");
            btnBuscar.setText("Cancelar");
            txtCodigo.setEnabled(false);
            btnDeletar.setEnabled(false);
            btnAlterar.setEnabled(false);
            txtCodigo.setText(gerarID());
            return;
        }
        
        if(verificarCamposVazios() && btnCadastrar.getText().equals("Salvar")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
            return;
        }
        if(btnCadastrar.getText().equals("Salvar")){
            produto.setCodigo(txtCodigo.getText());
            produto.setNome(txtProduto.getText());
            produto.setPreco(Double.parseDouble(txtPreço.getText().replace(",", ".")));
            produto.setQuantidadeEstoque(Integer.parseInt(txtQuantidade.getText()));
            try {
                ProdutoDAO.inserir(produto);
                JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso!");
                limparCampos();
            } catch (SQLException | ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar produto!\n"+ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private String gerarID() {
        Produto  produto = new Produto();
        try {
            produto = ProdutoDAO.buscarUltimo();
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar ultimo produto!\n"+e.getMessage());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar ultimo produto!\n"+e.getMessage());
        }
        int i = Integer.parseInt(produto.getCodigo());
        i++;
        String id = ""+i;
        return id;
    }

    private boolean verificarCamposVazios() {
        if(
            txtProduto.getText().length() <= 0
            || txtQuantidade.getText().length() <= 0
            || txtPreço.getText().length() <= 0
        ){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para continuar");
            return true;//não contém dados
        }
        return false; //contém dados
    }

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        //        Model.Produto produto = new Model.Produto();
        DefaultTableModel modelo = (DefaultTableModel) jTblProdutos.getModel();
        int linhas_Selecionadas = jTblProdutos.getSelectedRowCount();
        if(linhas_Selecionadas == 0){
            JOptionPane.showMessageDialog(null, "Selecione uma linha para deletar");
            return;
        }

        int opcao = JOptionPane.showConfirmDialog(null, "Deseja deletar o(s) registro(s) selecionado(s)?", "Atenção", JOptionPane.YES_NO_OPTION);
        if(opcao == JOptionPane.NO_OPTION){
            return;
        }
        for(int i = 0; i < linhas_Selecionadas; i++){
            // int id_produto = (int)
            int id_produto = Integer.parseInt(modelo.getValueAt(jTblProdutos.getSelectedRow(), 0).toString());
            try {
                ProdutoDAO.deletar(id_produto);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Erro ao deletar o registro");
                e.printStackTrace();
            }
            modelo.removeRow(jTblProdutos.getSelectedRow());
        }
        JOptionPane.showMessageDialog(null, "Registro(s) deletado(s) com sucesso");
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        int linhaSelecionada = jTblProdutos.getSelectedRow();
        Produto produto = new Produto();
        if(linhaSelecionada <= 0) {
            JOptionPane.showMessageDialog(null, "Selecione um produto para alterar");
            return;
        }
        setProdutoComValoresDaLinha(produto, linhaSelecionada);
        if(btnAlterar.getText().equals("Salvar") && !verificarCamposVazios()){
            try {
                produto = atualizarValoresProduto(produto);
                produto = ProdutoDAO.alterar(produto);
                JOptionPane.showMessageDialog(null, "Produto alterado com sucesso!");
                limparCampos();
                resetarComponentes();
                atualizarTabela();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Erro ao alterar o registro\n"+e);
                e.printStackTrace();
            }
            return;
        }
        
        btnAlterar.setText("Salvar");
        btnBuscar.setText("Cancelar");
        btnCadastrar.setEnabled(false);
        btnDeletar.setEnabled(false);
        jTblProdutos.setEnabled(false);
        setCamposParaAlteração(produto);
        txtCodigo.setEnabled(false);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private Produto atualizarValoresProduto(Produto produto) {
        produto.setCodigo(txtCodigo.getText());
        produto.setNome(txtProduto.getText());
        produto.setPreco(Double.parseDouble(txtPreço.getText().replace(",", ".")));
        produto.setQuantidadeEstoque(Integer.parseInt(txtQuantidade.getText()));
        return produto;
    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if(btnBuscar.getText().equals("Cancelar")){
            limparCampos();
            resetarComponentes();
        }

        ArrayList<Produto> produtos = new ArrayList<>();
        if (txtProduto.getText().length() > 0){//texto produto
            try {
                produtos = ProdutoDAO.consultarPorNome(txtProduto.getText());//consultar por nome
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(CadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(txtCodigo.getText().length() > 0){//texto codigo
            try {
                int codigo = Integer.parseInt(txtCodigo.getValue().toString());
                produtos = ProdutoDAO.consultarPorCodigo(codigo);//por código
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(CadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{//nem um nem outro
            try {
                produtos = ProdutoDAO.consultar();
            } catch (ClassNotFoundException | SQLException e) {
                JOptionPane.showMessageDialog(null, "Erro ao consultar produtos!");
                e.printStackTrace();
            }
        }
        atualizarTabela(produtos);
        limparCampos();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnUtilizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUtilizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUtilizarActionPerformed

    private void resetarComponentes() {
        limparCampos();
        atualizarTabela();
        btnAlterar.setText("Alterar");
        btnBuscar.setText("Buscar");
        btnCadastrar.setText("Cadastrar");
        btnDeletar.setText("Deletar");

        txtCodigo.setEnabled(true);

        btnCadastrar.setEnabled(true);
        btnAlterar.setEnabled(true);
        btnDeletar.setEnabled(true);
        btnBuscar.setEnabled(true);

        jTblProdutos.setEnabled(true);
    }

    private void limparCampos() {
        txtCodigo.setText("");
        txtProduto.setText("");
        txtQuantidade.setText("");
        txtPreço.setText("");
    }

    private void setCamposParaAlteração(Produto produto) {
        txtCodigo.setText(produto.getCodigo());
        txtProduto.setText(produto.getNome());
        txtQuantidade.setText(String.valueOf(produto.getQuantidadeEstoque()));
        txtPreço.setText(String.valueOf(produto.getPreco()));
    }

    private void setProdutoComValoresDaLinha(Produto produto, int linhaSelecionada) {
        DefaultTableModel modelo = (DefaultTableModel) jTblProdutos.getModel();
        produto.setCodigo((modelo.getValueAt(linhaSelecionada, 0).toString()));
        produto.setNome(modelo.getValueAt(linhaSelecionada, 1).toString());
        produto.setQuantidadeEstoque(Integer.parseInt(modelo.getValueAt(linhaSelecionada, 2).toString())); //strin pra int
        produto.setPreco(Double.parseDouble(modelo.getValueAt(linhaSelecionada, 3).toString())); //string pra double
    }

    private void atualizarTabela(ArrayList<Produto> produtos) {
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) jTblProdutos.getModel();
        model.setNumRows(0);
        for (Produto p : produtos) {
            model.addRow(new Object[]{
                p.getCodigo(),//TODO: pegar id_cliente;
                p.getNome(),
                p.getQuantidadeEstoque(),
                p.getPreco()
            });
        }
    }
    private void atualizarTabela() {
        ArrayList<Produto> produtos = new ArrayList<>();
        try {
            produtos = ProdutoDAO.consultar();
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao consultar produtos!");
            e.printStackTrace();
        }
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) jTblProdutos.getModel();
        model.setNumRows(0);
        for (Produto p : produtos) {
            model.addRow(new Object[]{
                p.getCodigo(),
                p.getNome(),
                p.getQuantidadeEstoque(),
                p.getPreco()
            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnUtilizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblProdutos;
    private javax.swing.JFormattedTextField txtCodigo;
    private javax.swing.JFormattedTextField txtPreço;
    private javax.swing.JFormattedTextField txtProduto;
    private javax.swing.JFormattedTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
